#pragma once
constexpr int NUM_STARTING_ASTEROIDS = 6;
constexpr int MAX_ASTEROIDS = 100;
constexpr int MAX_BULLETS = 50;
constexpr int MAX_BEETLES = 50;
constexpr int MAX_WASPS = 50;
constexpr int MAX_DEBRIS = 200;
constexpr int MAX_DEBRIS_SUBDIVISION = 8;
constexpr int MAX_ATTRACTMODE_BOIDS = 1000;
constexpr int DEBUG_DRAWRING_SUBDIVISION = 32;
constexpr float WORLD_SIZE_X = 200.f;
constexpr float WORLD_SIZE_Y = 100.f;
constexpr float WORLD_CENTER_X = WORLD_SIZE_X / 2.f;
constexpr float WORLD_CENTER_Y = WORLD_SIZE_Y / 2.f;
constexpr float SCREEN_SIZE_X = 1600.f;
constexpr float SCREEN_SIZE_Y = 800.f;
constexpr float SCREEN_CENTER_X = SCREEN_SIZE_X / 2.f;
constexpr float SCREEN_CENTER_Y = SCREEN_SIZE_Y / 2.f;
constexpr float ASTEROID_SPEED = 10.f;
constexpr float ASTEROID_PHYSICS_RADIUS = 1.6f;
constexpr float ASTEROID_COSMETIC_RADIUS = 2.0f;
constexpr float BULLET_LIFETIME_SECONDS = 2.0f;
constexpr float BULLET_SPEED = 50.f;
constexpr float BULLET_PHYSICS_RADIUS = 0.5f;
constexpr float BULLET_COSMETIC_RADIUS = 2.0f;
constexpr float PLAYER_SHIP_ACCELERATION = 30.f;
constexpr float PLAYER_SHIP_TURN_SPEED = 300.f;
constexpr float PLAYER_SHIP_PHYSICS_RADIUS = 1.75f;
constexpr float PLAYER_SHIP_COSMETIC_RADIUS = 2.25f;
constexpr float ENEMY_BEETLE_SPEED = 9.f;
constexpr float ENEMY_BEETLE_PHYSICS_RADIUS = 1.75f;
constexpr float ENEMY_BEETLE_COSMETIC_RADIUS = 2.25f;
constexpr float ENEMY_WASP_ACCELERATION = 10.f;
constexpr float ENEMY_WASP_MAX_SPEED = 30.f;
constexpr float ENEMY_WASP_PHYSICS_RADIUS = 1.75f;
constexpr float ENEMY_WASP_COSMETIC_RADIUS = 2.25f;
constexpr float DEBRIS_PHYSICS_RADIUS = 0.2f;
constexpr float DEBRIS_COSMETIC_RADIUS = 1.2f;

struct Vec2;
struct Rgba8;

void DebugDrawLine(Vec2 startPosition, Vec2 endPosition, Rgba8 lineCOlor, float thickness);
void DebugDrawRing(Vec2 centre, float radius, Rgba8 ringColor, float thickness);
