#pragma once
constexpr int   NUM_STARTING_ASTEROIDS       = 6;
constexpr int   MAX_ASTEROIDS                = 2000;
constexpr int   MAX_BULLETS                  = 3000;
constexpr int   MAX_BEETLES                  = 1100;
constexpr int   MAX_WASPS                    = 1100;
constexpr int   MAX_DEBRIS                   = 2000;
constexpr int   MAX_SHOCKWAVE                = 1000;
constexpr int   MAX_DEBRIS_SUBDIVISION       = 8;
constexpr int   MAX_ATTRACTMODE_STAR         = 6000;
constexpr int   MAX_ATTRACTMODE_BOIDS        = 1000;
constexpr int   MAX_NEAR_STAR                = 6000;
constexpr int   MAX_FAR_STAR                 = 12000;
constexpr int   DEBUG_DRAWRING_SUBDIVISION   = 32;
constexpr float WORLD_SIZE_X                 = 1000.f;
constexpr float WORLD_SIZE_Y                 = 1000.f;
constexpr float WORLD_CENTER_X               = WORLD_SIZE_X / 2.f;
constexpr float WORLD_CENTER_Y               = WORLD_SIZE_Y / 2.f;
constexpr float VIEW_SIZE_X                  = 300.f;
constexpr float VIEW_SIZE_Y                  = 150.f;
constexpr float VIEW_CENTER_X                = VIEW_SIZE_X / 2.f;
constexpr float VIEW_CENTER_Y                = VIEW_SIZE_Y / 2.f;
constexpr float SCREEN_SIZE_X                = 1600.f;
constexpr float SCREEN_SIZE_Y                = 800.f;
constexpr float SCREEN_CENTER_X              = SCREEN_SIZE_X / 2.f;
constexpr float SCREEN_CENTER_Y              = SCREEN_SIZE_Y / 2.f;
constexpr float ASTEROID_SPEED               = 10.f;
constexpr float ASTEROID_PHYSICS_RADIUS      = 1.6f;
constexpr float ASTEROID_COSMETIC_RADIUS     = 2.0f;
constexpr float BULLET_LIFETIME_SECONDS      = 2.0f;
constexpr float BULLET_SPEED                 = 150.f;
constexpr float BULLET_PHYSICS_RADIUS        = 0.5f;
constexpr float BULLET_COSMETIC_RADIUS       = 2.0f;
constexpr float PLAYER_MAX_SPEED             = 100.f;
constexpr float PLAYER_SHIP_ACCELERATION     = 30.f;
constexpr float PLAYER_SHIP_TURN_SPEED       = 300.f;
constexpr float PLAYER_SHIP_PHYSICS_RADIUS   = 1.75f;
constexpr float PLAYER_SHIP_COSMETIC_RADIUS  = 2.25f;
constexpr float ENEMY_BEETLE_SPEED           = 40.f;
constexpr float ENEMY_BEETLE_PHYSICS_RADIUS  = 1.75f;
constexpr float ENEMY_BEETLE_COSMETIC_RADIUS = 2.25f;
constexpr float ENEMY_BEETLE_NEARBY_RADIUS   = 30.f;
constexpr float ENEMY_WASP_SPEED             = 120.f;
constexpr float ENEMY_WASP_PHYSICS_RADIUS    = 1.75f;
constexpr float ENEMY_WASP_COSMETIC_RADIUS   = 2.25f;
constexpr float ENEMY_WASP_NEARBY_RADIUS     = 80.f;
constexpr float DEBRIS_PHYSICS_RADIUS        = 0.2f;
constexpr float DEBRIS_COSMETIC_RADIUS       = 1.2f;

struct Vertex;
struct Vec2;
struct Rgba8;

void DrawLine(Vec2 startPosition, Vec2 endPosition, Rgba8 lineCOlor, float thickness);
void DrawRing(Vec2 centre, float radius, Rgba8 ringColor, float thickness);
void DrawDisc(Vec2 centre, float radius, Rgba8 outerColor, Rgba8 innerColor);
void DrawAABB(Vec2 buttomLeft, Vec2 topRight, Rgba8 leftColor, Rgba8 rightColor, Rgba8 centerColor);
void TransformVertexArrayShine(int numVerts, Vertex* verts, float uniformScaleXY, float rotationDegreesAboutZ, Vec2 const& translationXY, float time);
void TransformVertexArrayScaleNoneUniform(int numVerts, Vertex* verts, Vec2 scaleXY, float rotationDegreesAboutZ, Vec2 const& translationXY);
